### ISSUE TITLE
No compatiblity with Python 3.10

### ISSUE THREAD

**Issue by popotam** [Fatal1ty/aioapns#31]
Hi, I'm getting the following error on Python 3.10

```[ios exc] As of 3.10, the *loop* parameter was removed from Lock() since it is no longer necessary", "exc_info": "Traceback (most recent call last):
  File "/opt/webapps/notification/tasks/push.py", line 368, in apns_push_task
    conn = apns_client.get_connection(profile_type, is_tablet)
  File "/opt/lib/apple/apns_client.py", line 31, in get_connection
    return _get_mobile_connection(app)
  File "/opt/lib/apple/apns_client.py", line 37, in _get_mobile_connection
    _CLIENTS[app] = APNs(
  File "/usr/local/lib/python3.10/site-packages/aioapns/client.py", line 26, in __init__
    self.pool = APNsCertConnectionPool(
  File "/usr/local/lib/python3.10/site-packages/aioapns/connection.py", line 402, in __init__
    super(APNsCertConnectionPool, self).__init__(
  File "/usr/local/lib/python3.10/site-packages/aioapns/connection.py", line 307, in __init__
    self._lock = asyncio.Lock(loop=self.loop)
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 77, in __init__
    super().__init__(loop=loop)
  File "/usr/local/lib/python3.10/asyncio/mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Lock() since it is no longer necessary```

**Comment by Fatal1ty** [comment]
Hi @popotam 
Could you please check https://github.com/Fatal1ty/aioapns/pull/32?

**Comment by popotam** [comment]
Looks great!
I'll close this one.
