### ISSUE TITLE
How to form the certificate

### ISSUE THREAD

**Issue by oculos** [Fatal1ty/aioapns#48]
Hi,

In Apple's examples with curl, one needs to provide both the key and the certificate for certificate-based push.
I don't see the configuration for a key here. Does it need to be included in the pem?

**Comment by Fatal1ty** [comment]
Hi,

Have you tried to pass `key_id` parameter along with path to your certificate?

**Comment by oculos** [comment]
> Hi,
> 
> Have you tried to pass `key_id` parameter along with path to your certificate?

Thanks. Just did. Got this: 

```
Traceback (most recent call last):
  File "/root/push/send_push.py", line 30, in <module>
    loop.run_until_complete(run())
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/root/push/send_push.py", line 9, in run
    apns_cert_client = APNs(
  File "/usr/local/lib/python3.9/site-packages/aioapns/client.py", line 37, in __init__
    self.pool = APNsCertConnectionPool(
  File "/usr/local/lib/python3.9/site-packages/aioapns/connection.py", line 455, in __init__
    self.ssl_context.load_cert_chain(cert_file)
ssl.SSLError: [SSL] PEM lib (_ssl.c:4044)
(venv) [fra@push-test push]# nano send_push.py
```

**Comment by oculos** [comment]
Nevermind, it was my own fault. No need of the `key_id`, I just had to combine the key and cert on a pem certificate.
