### ISSUE TITLE
Any compatibility with uvloop?

### ISSUE THREAD

**Issue by bekzat-shayakhmet** [Fatal1ty/aioapns#54]
Is the package compatible with uvloop? Getting assertion error while trying to send a request.

https://github.com/Fatal1ty/aioapns/blob/master/aioapns/connection.py#L91

```
Fatal error on transport TCPTransport
protocol: <uvloop.loop.SSLProtocol object at 0xffffa482f320>
transport: <TCPTransport closed=False reading=False 0xaaab13595100>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 1007, in uvloop.loop.__uv_stream_buffered_on_read
  File "uvloop/loop.pyx", line 109, in uvloop.loop.run_in_context1
  File "uvloop/sslproto.pyx", line 379, in uvloop.loop.SSLProtocol.buffer_updated
  File "uvloop/sslproto.pyx", line 505, in uvloop.loop.SSLProtocol._do_handshake
  File "uvloop/sslproto.pyx", line 541, in uvloop.loop.SSLProtocol._on_handshake_complete
  File "/tmp/.venv/lib/python3.10/site-packages/aioapns/connection.py", line 169, in connection_made
    super(APNsBaseClientProtocol, self).connection_made(transport)
  File "/tmp/.venv/lib/python3.10/site-packages/aioapns/connection.py", line 91, in connection_made
    assert isinstance(transport, asyncio.Transport)
AssertionError
```

**Comment by Fatal1ty** [comment]
Fixed in https://github.com/Fatal1ty/aioapns/pull/58
