### ISSUE TITLE
Failing to connect to APNS - MaxAttemptsExceeded

### ISSUE THREAD

**Issue by harrymoy** [Fatal1ty/aioapns#55]
My server is currently failing when using aioapns when trying to push a notification to a device. This was working a few days ago, but I'm now getting `MaxAttemptsExceeded`

```
2024-02-24T14:08:56.680 app[6e82e50c290e08] lhr [info] ERROR:asyncio:Exception in callback <bound method APNsBaseClientProtocol.connection_lost of <aioapns.connection.APNsDevelopmentClientProtocol object at 0x7fdc1ffc2680>>

2024-02-24T14:08:56.680 app[6e82e50c290e08] lhr [info] handle: <Handle APNsBaseClientProtocol.connection_lost>

2024-02-24T14:08:56.680 app[6e82e50c290e08] lhr [info] Traceback (most recent call last):

2024-02-24T14:08:56.680 app[6e82e50c290e08] lhr [info] File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run

2024-02-24T14:08:56.680 app[6e82e50c290e08] lhr [info] File "/usr/local/lib/python3.10/site-packages/aioapns/connection.py", line 243, in connection_lost

2024-02-24T14:08:56.680 app[6e82e50c290e08] lhr [info] self.on_connection_lost(self)

2024-02-24T14:08:56.680 app[6e82e50c290e08] lhr [info] File "/usr/local/lib/python3.10/site-packages/aioapns/connection.py", line 355, in discard_connection

2024-02-24T14:08:56.680 app[6e82e50c290e08] lhr [info] self.connections.remove(connection)

2024-02-24T14:08:56.680 app[6e82e50c290e08] lhr [info] ValueError: list.remove(x): x not in list

2024-02-24T14:08:56.684 app[6e82e50c290e08] lhr [info] ERROR:aioapns:Could not connect to server:

2024-02-24T14:08:56.687 app[6e82e50c290e08] lhr [info] WARNING:aioapns:Could not send notification c416e334-bed3-4c89-a099-0ec429d3d398: ConnectionError
```

**Comment by Fatal1ty** [comment]
Hi @harrymoy 

Can you check if [3.2](https://github.com/Fatal1ty/aioapns/releases/tag/v3.2) solves this problem?
