### ISSUE TITLE
Typing hints fail under CPython 3.7.1

### ISSUE THREAD

**Issue by vaizki** [Fatal1ty/aioapns#9]
Under Python 3.7.1, even importing the module fails.. 

```# /usr/local/bin/python3.7
Python 3.7.1 (default, Apr  3 2019, 17:03:30)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import aioapns
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/aioapns/__init__.py", line 1, in <module>
    from aioapns.client import APNs
  File "/usr/local/lib/python3.7/site-packages/aioapns/client.py", line 4, in <module>
    from aioapns.connection import APNsCertConnectionPool, APNsKeyConnectionPool
  File "/usr/local/lib/python3.7/site-packages/aioapns/connection.py", line 126, in <module>
    class APNsBaseClientProtocol(H2Protocol):
  File "/usr/local/lib/python3.7/site-packages/aioapns/connection.py", line 135, in APNsBaseClientProtocol
    auth_provider: Optional[AuthorizationHeaderProvider] = None):
  File "/usr/local/lib/python3.7/typing.py", line 755, in __getitem__
    return self.__getitem_inner__(params)
  File "/usr/local/lib/python3.7/typing.py", line 251, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.7/typing.py", line 774, in __getitem_inner__
    result = _type_check(result, msg)
  File "/usr/local/lib/python3.7/typing.py", line 135, in _type_check
    raise TypeError(f"Plain {arg} is not valid as type argument")
TypeError: Plain typing.NoReturn is not valid as type argument
```

**Comment by vaizki** [comment]
Ok I was hasty.. it's caused by this https://bugs.python.org/issue34921 .. and yes it works under 3.7.2 and 3.7.3 (tested it) so just 3.7.1 is affected.
